export interface Location {
  id: string
  name: string
  address: string
  type: 'food' | 'view' | 'activity' | 'nightlife' | 'nature' | 'culture'
  time: string
  duration: string
  cost: string
  costAmount: number
  description: string
  tips: string[]
  mapsUrl: string
  priority: 'must-see' | 'recommended' | 'optional'
  emoji: string
}

export const austinItinerary: Location[] = [
  {
    id: 'ut-campus',
    name: 'UT Campus',
    address: '2828 Rio Grande St, Austin, TX 78705',
    type: 'culture',
    time: '10:00 AM',
    duration: '1h 15min',
    cost: 'Free',
    costAmount: 0,
    description: 'Start at the beautiful UT Tower, Littlefield Fountain, and walk The Drag for classic Austin college vibes',
    tips: ['Park near Guadalupe St', 'Tower views are iconic', 'Great photo ops at South Mall'],
    mapsUrl: 'https://maps.google.com/?q=UT+Tower+Austin',
    priority: 'must-see',
    emoji: '🎓'
  },
  {
    id: 'cabo-bobs',
    name: "Cabo Bob's",
    address: '2828 Rio Grande St, Austin, TX 78705',
    type: 'food',
    time: '11:15 AM',
    duration: '45min',
    cost: '$12-15',
    costAmount: 13.5,
    description: 'Fuel up with an amazing burrito bowl. Fresh ingredients, walking distance from UT',
    tips: ['Get there before noon rush', 'Try their signature queso', 'Walking distance from campus'],
    mapsUrl: 'https://maps.google.com/?q=Cabo+Bobs+Austin+Rio+Grande',
    priority: 'must-see',
    emoji: '🌯'
  },
  {
    id: 'capitol',
    name: 'Texas Capitol Mall',
    address: '1100 Congress Ave, Austin, TX 78701',
    type: 'culture',
    time: '12:00 PM',
    duration: '30min',
    cost: 'Free',
    costAmount: 0,
    description: 'The iconic Texas Capitol with wide walkways perfect for photos',
    tips: ['10min walk from UT', 'Beautiful architecture', 'Government district vibes'],
    mapsUrl: 'https://maps.google.com/?q=Texas+State+Capitol+Austin',
    priority: 'must-see',
    emoji: '🏛️'
  },
  {
    id: 'congress-bridge',
    name: 'Congress Avenue Bridge',
    address: 'Congress Ave Bridge, Austin, TX 78704',
    type: 'nature',
    time: '12:45 PM',
    duration: '45min',
    cost: 'Free',
    costAmount: 0,
    description: 'Walk the bridge, see Lady Bird Lake and the Austin skyline. This is where the famous bats fly at sunset!',
    tips: ['Park near South Congress', 'Walk the boardwalk', 'Return here for sunset bats at 7:50 PM'],
    mapsUrl: 'https://maps.google.com/?q=Congress+Avenue+Bridge+Austin',
    priority: 'must-see',
    emoji: '🌉'
  },
  {
    id: 'lady-bird',
    name: 'Lady Bird Lake Trail',
    address: 'Ann & Roy Butler Hike & Bike Trail',
    type: 'nature',
    time: '1:30 PM',
    duration: '45min',
    cost: 'Free',
    costAmount: 0,
    description: 'Scenic walk with water views, city skyline, boats, and hills. Super pretty for photos',
    tips: ['Walk 20-30 min and turn around', 'Bring water', 'Great for people watching'],
    mapsUrl: 'https://maps.google.com/?q=Lady+Bird+Lake+Trail+Austin',
    priority: 'must-see',
    emoji: '🚶‍♀️'
  },
  {
    id: 'long-center',
    name: 'Long Center Terrace',
    address: '701 W Riverside Dr, Austin, TX 78704',
    type: 'view',
    time: '2:00 PM',
    duration: '20min',
    cost: 'Free',
    costAmount: 0,
    description: 'One of THE BEST skyline views in all of Austin. Wide terrace, perfect for photos',
    tips: ['Quick stop near Zilker', 'Best skyline view in the city', 'Amazing photo backdrop'],
    mapsUrl: 'https://maps.google.com/?q=Long+Center+Austin',
    priority: 'must-see',
    emoji: '🏙️'
  },
  {
    id: 'chuys',
    name: 'First-Ever Chuys',
    address: '1728 Barton Springs Rd, Austin, TX 78704',
    type: 'culture',
    time: '2:15 PM',
    duration: '15min',
    cost: 'Free (drinks $5)',
    costAmount: 5,
    description: 'Historic Austin stop - the OG Chuys location. Grab a drink and soak in the vibes',
    tips: ['Quick stop', 'Fun Austin history', 'Right next to Zilker'],
    mapsUrl: 'https://maps.google.com/?q=Chuys+Barton+Springs+Austin',
    priority: 'recommended',
    emoji: '🌮'
  },
  {
    id: 'zilker',
    name: 'Zilker Park',
    address: '2100 Barton Springs Rd, Austin, TX 78746',
    type: 'nature',
    time: '2:30 PM',
    duration: '45min',
    cost: 'Free',
    costAmount: 0,
    description: 'Giant park with downtown views, perfect for walking around and seeing locals + dogs everywhere',
    tips: ['Can walk to Barton Springs Pool', 'Check out the botanical garden if time allows', 'Bring sunscreen'],
    mapsUrl: 'https://maps.google.com/?q=Zilker+Park+Austin',
    priority: 'must-see',
    emoji: '🌳'
  },
  {
    id: 'mozarts',
    name: 'Mozarts Coffee',
    address: '3825 Lake Austin Blvd, Austin, TX 78703',
    type: 'food',
    time: '3:15 PM',
    duration: '1h 15min',
    cost: '$8-12',
    costAmount: 10,
    description: 'Beautiful lakeside cafe with AMAZING tiramisu, pastries, and stunning views of Lake Austin',
    tips: ['Best cafe view in Austin', 'Get the tiramisu', 'Christmas lights if seasonal', 'Take your time here'],
    mapsUrl: 'https://maps.google.com/?q=Mozarts+Coffee+Austin',
    priority: 'must-see',
    emoji: '☕'
  },
  {
    id: 'mount-bonnell',
    name: 'Mount Bonnell',
    address: '3800 Mount Bonnell Rd, Austin, TX 78731',
    type: 'view',
    time: '4:30 PM',
    duration: '30min',
    cost: 'Free',
    costAmount: 0,
    description: 'Short 4-5min uphill stairs to ONE OF THE BEST panoramic views of Austin and the river',
    tips: ['Quick hike', 'Wear comfortable shoes', '10 mins from Mozarts'],
    mapsUrl: 'https://maps.google.com/?q=Mount+Bonnell+Austin',
    priority: 'recommended',
    emoji: '⛰️'
  },
  {
    id: 'mayfield-park',
    name: 'Mayfield Park (Peacocks)',
    address: '3505 W 35th St, Austin, TX 78703',
    type: 'nature',
    time: '5:00 PM',
    duration: '30min',
    cost: 'Free',
    costAmount: 0,
    description: 'Hidden gem! Free park with ponds and peacocks roaming freely. Super unique',
    tips: ['5 mins from Mount Bonnell', 'Peacocks everywhere', 'Great photo op'],
    mapsUrl: 'https://maps.google.com/?q=Mayfield+Park+Austin',
    priority: 'optional',
    emoji: '🦚'
  },
  {
    id: 'aba',
    name: 'Aba Restaurant',
    address: '1011 S Congress Ave, Austin, TX 78704',
    type: 'food',
    time: '5:45 PM',
    duration: '1h 15min',
    cost: '$40-60',
    costAmount: 50,
    description: 'Top-tier Mediterranean restaurant on South Congress. One of the best in Austin!',
    tips: ['Try for walk-in at bar/lounge', 'Backup: Perlas, Home Slice, or Cafe No Se nearby', 'Make reservation if possible'],
    mapsUrl: 'https://maps.google.com/?q=Aba+Restaurant+Austin',
    priority: 'must-see',
    emoji: '🍽️'
  },
  {
    id: 'south-congress',
    name: 'South Congress (SoCo)',
    address: 'S Congress Ave, Austin, TX 78704',
    type: 'culture',
    time: '7:00 PM',
    duration: '50min',
    cost: '$20-40 (shopping)',
    costAmount: 30,
    description: 'THE most iconic Austin street. Neon signs, boot stores, cute shops, amazing vibes',
    tips: ['Stop at Jos Coffee I Love You So Much wall', 'See Greetings From Austin mural', 'Great photo spots everywhere'],
    mapsUrl: 'https://maps.google.com/?q=South+Congress+Austin',
    priority: 'must-see',
    emoji: '✨'
  },
  {
    id: 'bats',
    name: 'Sunset + Bridge Bats',
    address: 'Congress Avenue Bridge, Austin, TX 78704',
    type: 'nature',
    time: '7:50 PM',
    duration: '30min',
    cost: 'Free',
    costAmount: 0,
    description: 'Watch the sunset over the water, then see 1.5 MILLION bats fly out from under the bridge. Iconic Austin moment!',
    tips: ['Timing varies by season (usually around 8 PM)', 'Arrive 10 mins early', 'One of Austins most famous attractions'],
    mapsUrl: 'https://maps.google.com/?q=Congress+Bridge+Bats+Austin',
    priority: 'must-see',
    emoji: '🦇'
  },
  {
    id: 'zeds',
    name: "Zeds Ice Cream",
    address: 'Multiple locations - SoCo area',
    type: 'food',
    time: '8:45 PM',
    duration: '20min',
    cost: '$6-8',
    costAmount: 7,
    description: 'New Zealand-style fruit ice cream. Perfect after-bats treat!',
    tips: ['Refreshing after a long day', 'Unique NZ-style', 'Quick stop'],
    mapsUrl: 'https://maps.google.com/?q=Zeds+Ice+Cream+Austin',
    priority: 'recommended',
    emoji: '🍦'
  },
  {
    id: 'west-6th',
    name: 'West 6th Street',
    address: 'W 6th St, Austin, TX 78701',
    type: 'nightlife',
    time: '9:30 PM',
    duration: '1h',
    cost: '$15-30 (drinks)',
    costAmount: 22.5,
    description: 'Trendy bar scene - more polished and classy than Dirty 6th. Good for a fun controlled night',
    tips: ['Choose between West 6th or Dirty 6th based on mood', 'Lots of rooftop bars', 'Good music'],
    mapsUrl: 'https://maps.google.com/?q=West+6th+Street+Austin',
    priority: 'recommended',
    emoji: '🍸'
  },
  {
    id: 'comedy-mothership',
    name: 'Joe Rogans Comedy Mothership',
    address: '612 E 6th St, Austin, TX 78701',
    type: 'nightlife',
    time: '10:30 PM',
    duration: '30min - 2h',
    cost: '$20-40 (show)',
    costAmount: 30,
    description: 'Joe Rogans comedy club! Walk by to see it, or catch a late show if tickets available',
    tips: ['Even just seeing the venue is cool', 'Check for last-minute tickets', 'Famous comedy spot'],
    mapsUrl: 'https://maps.google.com/?q=Comedy+Mothership+Austin',
    priority: 'recommended',
    emoji: '🎤'
  },
]
